In [1]:
#libraries involved 
import pandas as pd 
import numpy as np

In [6]:
train_data = pd.read_table("data/raw_data/drugsComTrain_raw.tsv")

In [7]:
train_data.head(10)

,Unnamed: 0,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37
5,155963,Cialis,Benign Prostatic Hyperplasia,"""2nd day on 5mg started to work with rock hard...",2.0,"November 28, 2015",43
6,165907,Levonorgestrel,Emergency Contraception,"""He pulled out, but he cummed a bit in me. I t...",1.0,"March 7, 2017",5
7,102654,Aripiprazole,Bipolar Disorde,"""Abilify changed my life. There is hope. I was...",10.0,"March 14, 2015",32
8,74811,Keppra,Epilepsy,""" I Ve had nothing but problems with the Kepp...",1.0,"August 9, 2016",11
9,48928,Ethinyl estradiol / levonorgestrel,Birth Control,"""I had been on the pill for many years. When m...",8.0,"December 8, 2016",1

In [8]:
train_data=train_data.rename(columns={"Unnamed: 0":"drug_id"})

In [9]:
train_data.head(10)

,drug_id,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37
5,155963,Cialis,Benign Prostatic Hyperplasia,"""2nd day on 5mg started to work with rock hard...",2.0,"November 28, 2015",43
6,165907,Levonorgestrel,Emergency Contraception,"""He pulled out, but he cummed a bit in me. I t...",1.0,"March 7, 2017",5
7,102654,Aripiprazole,Bipolar Disorde,"""Abilify changed my life. There is hope. I was...",10.0,"March 14, 2015",32
8,74811,Keppra,Epilepsy,""" I Ve had nothing but problems with the Kepp...",1.0,"August 9, 2016",11
9,48928,Ethinyl estradiol / levonorgestrel,Birth Control,"""I had been on the pill for many years. When m...",8.0,"December 8, 2016",1

In [11]:
train_data.to_csv("data/processed_data/drugsComTrain_Processed.csv")

In [12]:
# exploratory data analysis 
#library 
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
train_data.dtypes

drug_id          int64
drugName        object
condition       object
review          object
rating         float64
date            object
usefulCount      int64
dtype: object

In [14]:
train_data['drugName'].value_counts()
# try to sepearately take dataframe for each drug and explore it 
# for certain range of rating analyse the useful count an dalso analyse the review texts. [:)(: lots of love srirum :)(:]

drugName
Levonorgestrel                       3657
Etonogestrel                         3336
Ethinyl estradiol / norethindrone    2850
Nexplanon                            2156
Ethinyl estradiol / norgestimate     2117
                                     ...
Omnipaque 350                           1
Vontrol                                 1
Ivabradine                              1
Neo-Poly-Dex                            1
Grifulvin V                             1
Name: count, Length: 3436, dtype: int64

In [15]:
train_data['usefulCount'].describe()

count    161297.000000
mean         28.004755
std          36.403742
min           0.000000
25%           6.000000
50%          16.000000
75%          36.000000
max        1291.000000
Name: usefulCount, dtype: float64

In [16]:
train_data['rating'].describe()

count    161297.000000
mean          6.994377
std           3.272329
min           1.000000
25%           5.000000
50%           8.000000
75%          10.000000
max          10.000000
Name: rating, dtype: float64

In [17]:
train_data['condition'].unique()

array(['Left Ventricular Dysfunction', 'ADHD', 'Birth Control',
       'Opiate Dependence', 'Benign Prostatic Hyperplasia',
       'Emergency Contraception', 'Bipolar Disorde', 'Epilepsy',
       'Migraine Prevention', 'Depression', "Crohn's Disease", 'Cough',
       'Obesity', 'Urinary Tract Infection', 'ibromyalgia',
       'Chronic Myelogenous Leukemia', 'HIV Infection', 'Insomnia',
       'Rheumatoid Arthritis', 'Vaginal Yeast Infection',
       'Chlamydia Infection', 'Hirsutism', 'Panic Disorde', 'Migraine',
       nan, 'Pain', 'Irritable Bowel Syndrome', 'Osteoarthritis',
       'Constipation', 'Bowel Preparation', 'Psychosis', 'Muscle Spasm',
       'Hepatitis C', 'Overactive Bladde', 'Diabetes, Type 2',
       'Asthma, Maintenance', 'Non-Small Cell Lung Cance',
       'Schizophrenia', 'Dysuria', 'Smoking Cessation', 'Anxiety', 'Acne',
       'emale Infertility', 'Constipation, Acute',
       'Constipation, Drug Induced', 'Erectile Dysfunction',
       'Trigeminal Neuralgia', 'Underactive Thyroid', 'Chronic Pain',
       'Atrophic Vaginitis', 'Skin and Structure Infection', 'Tinnitus',
       'Major Depressive Disorde', 'Anxiety and Stress', 'Rosacea',
       'High Blood Pressure',
       '2</span> users found this comment helpful.',
       'Restless Legs Syndrome',
       'Osteolytic Bone Metastases of Solid Tumors', 'Bronchitis',
       'Skin or Soft Tissue Infection', 'Obsessive Compulsive Disorde',
       'Endometriosis', 'Keratoconjunctivitis Sicca', 'Breakthrough Pain',
       'Seizures', 'Neuropathic Pain', 'Sedation', 'Menstrual Disorders',
       'Allergic Rhinitis', 'Anesthesia',
       'Undifferentiated Connective Tissue Disease', 'Diabetes, Type 1',
       'Abnormal Uterine Bleeding', 'Weight Loss',
       'Constipation, Chronic', 'Breast Cancer, Metastatic',
       'Period Pain', 'Helicobacter Pylori Infection',
       'Atrial Fibrillation', 'Uterine Fibroids',
       '4</span> users found this comment helpful.', 'Kidney Infections',
       'Generalized Anxiety Disorde', 'Asthma', 'Postmenopausal Symptoms',
       'High Cholesterol', 'Hypogonadism, Male', 'Hyperthyroidism',
       'Back Pain', 'Anaplastic Oligodendroglioma', "Sjogren's Syndrome",
       'Asthma, acute', 'Hot Flashes',
       '3</span> users found this comment helpful.',
       'Herpes Simplex, Suppression', 'Bacterial Infection', 'Bursitis',
       'Diaper Rash', 'Systemic Mastocytosis', 'Trichotillomania',
       "Hashimoto's disease", 'Eczema', 'Dental Abscess', 'Headache',
       'Hypersomnia', 'Xerostomia', 'Breast Cance', 'Sore Throat',
       "Barrett's Esophagus", 'Pain/Feve', 'Diverticulitis', 'Sinusitis',
       'Polycystic Ovary Syndrome', 'Influenza',
       'Hypothyroidism, After Thyroid Removal', 'Onychomycosis, Toenail',
       'Progesterone Insufficiency',
       '11</span> users found this comment helpful.', 'GERD',
       'Nausea/Vomiting, Postoperative', 'Herpes Simplex',
       'Gastroparesis', 'Gout, Acute', 'Motion Sickness',
       'Multiple Sclerosis', 'Autism', 'Otitis Media',
       'Upper Respiratory Tract Infection', 'Surgical Prophylaxis',
       'Psoriatic Arthritis', 'Erosive Esophagitis',
       'Premature Ventricular Depolarizations', 'Stomach Ulce',
       'Nausea/Vomiting', 'Light Anesthesia',
       'Angina Pectoris Prophylaxis',
       '0</span> users found this comment helpful.', 'Paranoid Disorde',
       'Prostatitis', 'Extrapyramidal Reaction', 'mance Anxiety',
       'Night Terrors', 'High Cholesterol, Familial Heterozygous',
       'Spondyloarthritis', 'Clostridial Infection', 'Dermatomyositis',
       'Bronchiectasis', 'Nasal Congestion', 'Benign Essential Trem',
       'Angina', 'moterol / mometasone)', 'Impetig',
       'Conjunctivitis, Bacterial', 'Post Traumatic Stress Disorde',
       'Alcohol Withdrawal', 'Psoriasis', 'Cold Sores', 'Hyperhidrosis',
       '1</span> users found this comment helpful.',
       'Ankylosing Spondylitis', 'Hemorrhoids',
       '142</span> users found this comment helpful.',
       'Schizoaffective Disorde', 'Not Listed / Othe', 'Rhinitis',
       'Oral Thrush', 'Hyperlipoproteinemia',
       'Neutropenia Associated with Chemotherapy', 'Osteoporosis',
       'Reflex Sympathetic Dystrophy Syndrome', 'Urticaria', 'Narcolepsy',
       'Systemic Lupus Erythematosus', 'Ulcerative Colitis',
       'Adult Human Growth Hormone Deficiency', 'Bacterial Vaginitis',
       'COPD, Maintenance', 'Anorexia', 'TSH Suppression',
       'Breast Cancer, Adjuvant', 'Glaucoma',
       'Cough and Nasal Congestion',
       '8</span> users found this comment helpful.',
       'Inflammatory Conditions', 'Urinary Incontinence', 'Gout',
       'Bladder Infection', 'Human Papillomavirus Prophylaxis',
       'Glioblastoma Multiforme', 'Strep Throat',
       'Bacterial Skin Infection', 'Hereditary Angioedema',
       'Cold Symptoms', 'Labor Pain', 'Dry Skin', 'Diabetes Insipidus',
       'Methicillin-Resistant Staphylococcus Aureus Infection',
       'Borderline Personality Disorde', 'Amenorrhea', 'Pneumonia',
       'Seborrheic Dermatitis', 'Interstitial Cystitis',
       'Malaria Prevention', 'Prevention of Dental Caries',
       'Herbal Supplementation', 'Plaque Psoriasis', "Raynaud's Syndrome",
       "Addison's Disease", 'Prostate Cance', 'Allergies',
       'Opioid-Induced Constipation', 'moterol)',
       '13</span> users found this comment helpful.', 'Diarrhea',
       'Seasonal Allergic Conjunctivitis', 'Opioid Overdose',
       'Spondylolisthesis', 'Shift Work Sleep Disorde',
       'Obstructive Sleep Apnea/Hypopnea Syndrome',
       'Nausea/Vomiting of Pregnancy', 'Mucositis',
       'Ulcerative Colitis, Active', 'Head Lice',
       'Tonsillitis/Pharyngitis', 'Pseudotumor Cerebri',
       "Parkinson's Disease", 'Sciatica', 'Cance',
       'Bacterial Endocarditis Prevention', 'Diarrhea, Chronic',
       'Hypertensive Emergency', 'Keratosis', 'Ovarian Cysts',
       "Behcet's Disease", 'Chronic Idiopathic Constipation',
       'lic Acid Deficiency', 'Chronic Fatigue Syndrome',
       'Basal Cell Carcinoma', 'Cataplexy',
       "Crohn's Disease, Maintenance", 'Diabetic Peripheral Neuropathy',
       'Arrhythmia', 'Primary Ovarian Failure', 'Influenza Prophylaxis',
       'Agitated State', 'Heart Failure', 'atigue', 'Opiate Withdrawal',
       'Endometrial Hyperplasia, Prophylaxis', 'Immunosuppression',
       'Dystonia', 'Alopecia', 'Vulvodynia',
       'Premenstrual Dysphoric Disorde', 'Alcohol Dependence',
       'Myasthenia Gravis', 'Social Anxiety Disorde', 'Atopic Dermatitis',
       'Schistosoma japonicum', 'Sinus Symptoms', 'min / sitagliptin)',
       'Dermatitis', 'Eye Redness', 'Warts', 'Menorrhagia',
       'Seizure Prevention', 'Ophthalmic Surgery', 'Skin Rash',
       'Condylomata Acuminata', 'NSAID-Induced Ulcer Prophylaxis',
       'Tinea Versicol', 'Peripheral Neuropathy', 'Deep Vein Thrombosis',
       '6</span> users found this comment helpful.', 'Heart Attack',
       'Pulmonary Embolism, Recurrent Event', 'Light Sedation',
       'Acute Lymphoblastic Leukemia', 'Hyperprolactinemia',
       'Indigestion', 'Hepatitis B', 'Dysautonomia', 'Status Epilepticus',
       'Postpartum Depression', 'Multiple Myeloma',
       'Prevention of Hypokalemia', 'Edema', 'Urinary Retention',
       'Prevention of Thromboembolism in Atrial Fibrillation',
       'Cluster Headaches', 'Sexual Dysfunction, SSRI Induced',
       'Dermatitis Herpetiformis', 'Temporomandibular Joint Disorde',
       'Burns, External', 'Actinic Keratosis', 'Pharyngitis',
       'Melanoma, Metastatic', 'Atrial Flutte', 'Lyme Disease',
       'Dry Eye Disease', 'Allergic Reactions', 'Hypertriglyceridemia',
       'Pruritus', 'Carcinoid Tum', 'Muscle Pain', 'Colorectal Cance',
       'Vitamin/Mineral Supplementation during Pregnancy/Lactation',
       'Nausea/Vomiting, Chemotherapy Induced', 'Women (oxybutynin)',
       'Primary Immunodeficiency Syndrome',
       'New Daily Persistent Headache',
       'Pneumococcal Disease Prophylaxis', 'Burning Mouth Syndrome',
       'Urinary Tract Stones', 'Pseudobulbar Affect',
       '94</span> users found this comment helpful.',
       'Eye Redness/Itching', 'Deep Vein Thrombosis, First Event',
       'Pulmonary Hypertension', 'Malaria', 'Sarcoidosis',
       'Dietary Supplementation', 'Bulimia', 'Tendonitis', 'Nasal Polyps',
       'Hypokalemia', 'Anemia, Sickle Cell', 'Uveitis',
       'Streptococcal Infection', 'Perimenopausal Symptoms',
       'Asperger Syndrome', 'Tinea Corporis', 'Mania',
       'Renal Cell Carcinoma', 'COPD', 'Biliary Cirrhosis', 'Vertig',
       'Reversal of Opioid Sedation', "Non-Hodgkin's Lymphoma",
       'High Cholesterol, Familial Homozygous',
       'Periodic Limb Movement Disorde', 'Supraventricular Tachycardia',
       'Hypoestrogenism', 'Juvenile Idiopathic Arthritis', 'Swine Flu',
       'Giardiasis', 'Binge Eating Disorde', "Tourette's Syndrome",
       'Trichomoniasis', 'acial Wrinkles',
       '28</span> users found this comment helpful.',
       'Pulmonary Embolism', 'Conjunctivitis, Allergic',
       'Avian Influenza', '16</span> users found this comment helpful.',
       'Hemangioma', 'Nocturnal Leg Cramps', 'Thyroid Suppression Test',
       'Muscle Twitching', 'Pupillary Dilation',
       'Lennox-Gastaut Syndrome', 'Opiate Adjunct', 'Postoperative Pain',
       'Candida Urinary Tract Infection', 'Cerebral Spasticity',
       'Lipodystrophy', 'Androgenetic Alopecia', 'Computed Tomography',
       'Mitral Valve Prolapse', 'Vitamin D Deficiency',
       'Glaucoma, Open Angle', 'Endoscopy or Radiology Premedication',
       "Alzheimer's Disease", 'Gouty Arthritis',
       'Paroxysmal Supraventricular Tachycardia',
       'Deep Vein Thrombosis, Prophylaxis', 'Gaucher Disease',
       'Lymphocytic Colitis', 'Pancreatic Cance', 'Cystic Fibrosis',
       'Noninfectious Colitis',
       '27</span> users found this comment helpful.', 'Nephrocalcinosis',
       'Iron Deficiency Anemia', 'mulation) (phenylephrine)', 'Hiccups',
       '75</span> users found this comment helpful.',
       'Bronchospasm Prophylaxis', 'Chronic Spasticity',
       'min / saxagliptin)', 'Post-Cholecystectomy Diarrhea',
       'Postherpetic Neuralgia', 'Insomnia, Stimulant-Associated',
       'COPD, Acute', 'Herpes Simplex Dendritic Keratitis',
       'Oophorectomy', 'Cyclic Vomiting Syndrome',
       'Chronic Lymphocytic Leukemia', 'Lyme Disease, Arthritis',
       'Pseudomembranous Colitis', 'Conjunctivitis',
       '15</span> users found this comment helpful.', 'min)',
       'Intraocular Hypertension', 'Aphthous Ulce',
       'Ulcerative Colitis, Maintenance', 'Melasma',
       'Lyme Disease, Neurologic', 'ge (amlodipine / valsartan)',
       'Herpes Zoste', '12</span> users found this comment helpful.',
       'Cervical Dystonia', 'Labor Induction', 'Human Papilloma Virus',
       'Chronic Pancreatitis', 'Polycythemia Vera',
       '9</span> users found this comment helpful.',
       'Dermatological Disorders', 'Lewy Body Dementia',
       'amilial Mediterranean Feve', 'Neurosurgery', 'Gastroenteritis',
       'Macular Edema', 'Tinea Pedis',
       '7</span> users found this comment helpful.',
       'Diagnosis and Investigation',
       '35</span> users found this comment helpful.', 'Gas', 'Neuralgia',
       'Local Anesthesia', '54</span> users found this comment helpful.',
       'Acute Coronary Syndrome', 'Aspiration Pneumonia',
       'Idiopathic Thrombocytopenic Purpura', 'Onychomycosis, Fingernail',
       'Photoaging of the Skin', 'Premature Lab', 'Precocious Puberty',
       'Prevention of Bladder infection', 'Seasonal Affective Disorde',
       'Diabetic Kidney Disease', "Crohn's Disease, Acute",
       'Insulin Resistance Syndrome', 'Pudendal Neuralgia',
       "Reiter's Syndrome", '17</span> users found this comment helpful.',
       'Amyotrophic Lateral Sclerosis', 'Body Dysmorphic Disorde',
       'Prosthetic Heart Valves, Mechanical Valves - Thrombosis Prophylaxis',
       'Dandruff', 'Vitamin B12 Deficiency', 'Bone infection',
       'Prosthetic Heart Valves, Tissue Valves - Thrombosis Prophylaxis',
       'Iritis', 'Allergic Urticaria', 'Cardiovascular Risk Reduction',
       'Giant Cell Tumor of Bone', 'Babesiosis',
       'Secondary Hyperparathyroidism', 'Hypoparathyroidism',
       'Performance Anxiety', 'Abortion', 'Skin Cance',
       'Ovulation Induction', 'Liver Magnetic Resonance Imaging',
       'Vitamin/Mineral Supplementation and Deficiency',
       '79</span> users found this comment helpful.',
       'Herpes Simplex, Mucocutaneous/Immunocompetent Host',
       '10</span> users found this comment helpful.',
       'Anemia Associated with Chronic Renal Failure',
       'Hyperphosphatemia of Renal Failure',
       'Dissociative Identity Disorde', 'Anal Fissure and Fistula',
       '14</span> users found this comment helpful.',
       'Herpes Simplex, Mucocutaneous/Immunocompromised Host', 'Scabies',
       '5</span> users found this comment helpful.', 'Endometrial Cance',
       'Transient Ischemic Attack', 'Granuloma Annulare',
       "Traveler's Diarrhea", 'Candidemia',
       't Pac with Cyclobenzaprine (cyclobenzaprine)',
       'Hypoactive Sexual Desire Disorde', 'Epicondylitis, Tennis Elbow',
       'Nightmares', 'Dientamoeba fragilis', 'Ventricular Tachycardia',
       'Dumping Syndrome', 'Myelodysplastic Syndrome', 'Hypodermoclysis',
       'zen Shoulde', 'Topical Disinfection', 'Perioral Dermatitis',
       'Agitation', 'Intermittent Claudication',
       'Prevention of Osteoporosis', 'Leukemia', 'Dermatitis Herpeti',
       'mis', 'Eosinophilic Esophagitis',
       'Hyperlipoproteinemia Type IIa, Elevated LDL',
       'Endometrial Hyperplasia',
       '19</span> users found this comment helpful.', 'Peptic Ulce',
       'Chronic Myofascial Pain', 'Enterocolitis',
       'Secondary Cutaneous Bacterial Infections', 'Syringomyelia',
       'Postoperative Ocular Inflammation',
       'Persistent Depressive Disorde', 'Otitis Externa',
       'Organ Transplant, Rejection Prophylaxis',
       'Intermittent Explosive Disorde', 'Dermatophytosis',
       'Inflammatory Bowel Disease', 'Porphyria', 'Anemia',
       'Hyperuricemia Secondary to Chemotherapy',
       'Wolff-Parkinson-White Syndrome', 'eve', 'Ectopic Pregnancy',
       'Thyroid Cance', 'Tuberculosis, Latent',
       'Nasal Carriage of Staphylococcus aureus', 'Systemic Candidiasis',
       'Ear Wax Impaction', 'Hepatocellular Carcinoma', 'Dyspareunia',
       '41</span> users found this comment helpful.', 'Tic Disorde',
       'Head and Neck Cance', 'Klinefelter Syndrome', 'Rhinorrhea',
       'Soft Tissue Sarcoma', 'Diabetic Macular Edema',
       'Menopausal Disorders', 'Anesthetic Adjunct', 'Tinea Cruris',
       'tic (mycophenolic acid)', 'Ischemic Stroke', 'Malignant Glioma',
       'Thrombocythemia', 'Atrophic Urethritis', 'Systemic Sclerosis',
       'Macular Degeneration', 'AIDS Related Wasting', 'Hemophilia A',
       'Osteolytic Bone Lesions of Multiple Myeloma',
       'Autoimmune Hemolytic Anemia', 'ailure to Thrive',
       'Strongyloidiasis', 'Vitamin K Deficiency', 'Ulcerative Proctitis',
       'Premenstrual Syndrome',
       '23</span> users found this comment helpful.',
       'Primary Hyperaldosteronism', 'Lactose Intolerance',
       'Anal Itching', 'amilial Cold Autoinflammatory Syndrome',
       'Duodenal Ulce', 'Tuberculosis, Prophylaxis', 'Neurosis',
       "Turner's Syndrome", 'NSAID-Induced Gastric Ulce',
       'CNS Magnetic Resonance Imaging', 'Atherosclerosis',
       'Deep Vein Thrombosis Prophylaxis after Hip Replacement Surgery',
       'Gastritis/Duodenitis', 'Diarrhea, Acute', 'Costochondritis',
       'Portal Hypertension', 'Glaucoma/Intraocular Hypertension',
       'Toothache', 'Benzodiazepine Withdrawal', 'm Pain Disorde',
       'Esophageal Candidiasis',
       'Deep Vein Thrombosis Prophylaxis after Knee Replacement Surgery',
       'Peripheral Arterial Disease',
       'Deep Vein Thrombosis, Recurrent Event', 'Pseudogout, Prophylaxis',
       'Lichen Planus', 'CMV Prophylaxis',
       '64</span> users found this comment helpful.', 'Neuritis',
       'Typhoid Feve', 'Tardive Dyskinesia', 'Ichthyosis',
       'Juvenile Rheumatoid Arthritis', 'B12 Nutritional Deficiency',
       '18</span> users found this comment helpful.',
       'Primary Nocturnal Enuresis',
       '146</span> users found this comment helpful.', "Dercum's Disease",
       'Cutaneous Candidiasis', 'Gingivitis', 'Q Feve', 'Hyperekplexia',
       '44</span> users found this comment helpful.', 'Niacin Deficiency',
       'Dietary Fiber Supplementation', 'Nephrotic Syndrome',
       'Pinworm Infection (Enterobius vermicularis)',
       'Pancreatic Exocrine Dysfunction',
       'Nausea/Vomiting, Radiation Induced', 'Schilling Test',
       'Mild Cognitive Impairment', 'Ischemic Stroke, Prophylaxis',
       '20</span> users found this comment helpful.',
       'Gonococcal Infection, Uncomplicated', 'Ovarian Cance',
       'Eyelash Hypotrichosis', "Meniere's Disease", 'Tinea Capitis',
       '21</span> users found this comment helpful.', 'Lichen Sclerosus',
       'min / pioglitazone)', 'Renal Transplant', 'Gout, Prophylaxis',
       "von Willebrand's Disease",
       'Prevention of Atherothrombotic Events', 'Small Fiber Neuropathy',
       '110</span> users found this comment helpful.',
       'min / rosiglitazone)', "Peyronie's Disease",
       'Autoimmune Hepatitis', 'llicular Lymphoma',
       'Auditory Processing Disorde', 'Herpes Zoster, Prophylaxis',
       'Submental Fullness', 'Lactation Augmentation',
       'Radionuclide Myocardial Perfusion Study',
       'Prevention of Cardiovascular Disease', 'Varicella-Zoste',
       'Pelvic Inflammatory Disease', 'Intraabdominal Infection', 'Croup',
       '85</span> users found this comment helpful.',
       'Dermatologic Lesion',
       'Hyperlipoproteinemia Type IV, Elevated VLDL', 'Expectoration',
       'Primary Hyperaldosteronism Diagnosis', 'Abdominal Distension',
       'Salivary Gland Cance', 'Pulmonary Embolism, First Event',
       'Postpartum Breast Pain',
       'Postural Orthostatic Tachycardia Syndrome',
       '46</span> users found this comment helpful.',
       'Pediatric Growth Hormone Deficiency', 'Hypomagnesemia',
       'ge HCT (amlodipine / hydrochlorothiazide / valsartan)',
       'Hairy Cell Leukemia', 'Histoplasmosis', 'Hypoglycemia',
       '31</span> users found this comment helpful.', 'Brain Tum',
       'Gastrointestinal Stromal Tum', 'Tetanus',
       'Breast Cancer, Prevention', 'ICU Agitation', 'Women (minoxidil)',
       'Peripheral T-cell Lymphoma',
       'Chronic Inflammatory Demyelinating Polyradiculoneuropathy',
       'Pathological Hypersecretory Conditions',
       'Oral and Dental Conditions', 'Antiphospholipid Syndrome',
       'Ventricular Arrhythmia', 'Asystole', "Wegener's Granulomatosis",
       'Thromboembolic Stroke Prophylaxis',
       'Platelet Aggregation Inhibition', 'Sleep Paralysis',
       'Rejection Prophylaxis', 'Delayed Puberty, Male', 'Ascariasis',
       '25</span> users found this comment helpful.',
       'Acute Promyelocytic Leukemia',
       '32</span> users found this comment helpful.', 'Bartonellosis',
       'Cyclothymic Disorde', 'Hypokalemic Periodic Paralysis',
       'Varicose Veins', 'Mononucleosis', 'Cachexia', 'Hyperkalemia',
       "Still's Disease", '48</span> users found this comment helpful.',
       'Dementia', 'Ocular Rosacea', 'Hidradenitis Suppurativa', 'SIADH',
       'Bullous Pemphigoid', 'Angioedema',
       'Mountain Sickness / Altitude Sickness',
       'Severe Mood Dysregulation', 'Cutaneous T-cell Lymphoma',
       'Adrenocortical Insufficiency', 'Myxedema Coma',
       'Small Bowel Bacterial Overgrowth', 'Sunburn',
       '33</span> users found this comment helpful.',
       'Transverse Myelitis', 'Squamous Cell Carcinoma', 'Parkinsonism',
       '22</span> users found this comment helpful.', 'Thyrotoxicosis',

In [18]:
train_data_cleaned = train_data.dropna()

TO CHECK WHETHER THE NULL VALUES IN THE DATA FRAME REMOVED

In [19]:
print('Length of original data',len(train_data))
print(train_data.describe())
print('\n Length of cleansed data',len(train_data_cleaned))
train_data_cleaned.describe()

Length of original data 161297
             drug_id         rating    usefulCount
count  161297.000000  161297.000000  161297.000000
mean   115923.585305       6.994377      28.004755
std     67004.445170       3.272329      36.403742
min         2.000000       1.000000       0.000000
25%     58063.000000       5.000000       6.000000
50%    115744.000000       8.000000      16.000000
75%    173776.000000      10.000000      36.000000
max    232291.000000      10.000000    1291.000000

 Length of cleansed data 160398

             drug_id         rating    usefulCount
count  160398.000000  160398.000000  160398.000000
mean   115957.147309       6.995923      28.097613
std     67015.899492       3.272303      36.457876
min         2.000000       1.000000       0.000000
25%     58065.250000       5.000000       6.000000
50%    115845.500000       8.000000      16.000000
75%    173826.750000      10.000000      36.000000
max    232291.000000      10.000000    1291.000000

In [20]:
train_data_cleaned.head(10)

,drug_id,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37
5,155963,Cialis,Benign Prostatic Hyperplasia,"""2nd day on 5mg started to work with rock hard...",2.0,"November 28, 2015",43
6,165907,Levonorgestrel,Emergency Contraception,"""He pulled out, but he cummed a bit in me. I t...",1.0,"March 7, 2017",5
7,102654,Aripiprazole,Bipolar Disorde,"""Abilify changed my life. There is hope. I was...",10.0,"March 14, 2015",32
8,74811,Keppra,Epilepsy,""" I Ve had nothing but problems with the Kepp...",1.0,"August 9, 2016",11
9,48928,Ethinyl estradiol / levonorgestrel,Birth Control,"""I had been on the pill for many years. When m...",8.0,"December 8, 2016",1

TO REMOVE THE SPAM COMMENTS FROM CONDITIONS AND REPLCE THEM AS UNKNOWN

In [21]:
import re

In [22]:

comment = "62 </span> users found this comment helpful."

# Define a regular expression pattern to match the helpful count
pattern = r"(\d+)\s*</span> users found this comment helpful."

# Use re.search to find a match
match = re.search(pattern, comment)

In [23]:
user_found_comment_removal = train_data_cleaned[train_data_cleaned['condition'].str.contains(r'users found this comment helpful', regex=True)]

In [24]:
train_data_cleaned['condition'].loc[train_data_cleaned['condition'].str.contains(r'users found this comment helpful', regex=True)] = 'unknown'

C:\Users\Ramya\AppData\Local\Temp\ipykernel_7964\1029672864.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data_cleaned['condition'].loc[train_data_cleaned['condition'].str.contains(r'users found this comment helpful', regex=True)] = 'unknown'

In [25]:
len(train_data_cleaned[train_data_cleaned['condition']=='unknown'])

900

In [26]:
len(train_data_cleaned[train_data_cleaned['rating']=='unknown'])

0

In [27]:
train_data['rating'].value_counts()

rating
10.0    50989
9.0     27531
1.0     21619
8.0     18890
7.0      9456
5.0      8013
2.0      6931
3.0      6513
6.0      6343
4.0      5012
Name: count, dtype: int64

In [28]:
train_data_cleaned['rating'].value_counts()

rating
10.0    50745
9.0     27379
1.0     21504
8.0     18791
7.0      9395
5.0      7959
2.0      6879
3.0      6465
6.0      6301
4.0      4980
Name: count, dtype: int64

save new csv file with cleaned one

In [30]:
train_data_cleaned.to_csv('data/processed_data/drugsComTrain_cleaned.csv')

In [31]:
#plt.bar(train_data['drugName'],train_data['rating'])

In [32]:
train_data.head(10)

,drug_id,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37
5,155963,Cialis,Benign Prostatic Hyperplasia,"""2nd day on 5mg started to work with rock hard...",2.0,"November 28, 2015",43
6,165907,Levonorgestrel,Emergency Contraception,"""He pulled out, but he cummed a bit in me. I t...",1.0,"March 7, 2017",5
7,102654,Aripiprazole,Bipolar Disorde,"""Abilify changed my life. There is hope. I was...",10.0,"March 14, 2015",32
8,74811,Keppra,Epilepsy,""" I Ve had nothing but problems with the Kepp...",1.0,"August 9, 2016",11
9,48928,Ethinyl estradiol / levonorgestrel,Birth Control,"""I had been on the pill for many years. When m...",8.0,"December 8, 2016",1

DATA-PREPROCESSING FOR REVIEW COLUMN (TEXT FORMAT)

In [14]:
import spacy 
import nltk # natural language package similar to spacy 
import string
import re # regular expression
from nltk.corpus import stopwords
from tqdm import tqdm
import pandas as pd
import numpy as np

In [16]:
train_data_cleaned = pd.read_csv("data/processed_data/drugsComTrain_cleaned.csv")

In [17]:
def decontracted(phrase):
    # specific
    phrase = re.sub(r"won't", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)
    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    return phrase

In [18]:
def preprocess_text(text_data):

    text_data = decontracted(text_data)
    
    text_data = text_data.replace('\n',' ')
    text_data = text_data.replace('\r',' ')
    text_data = text_data.replace('\t',' ')
    text_data = text_data.replace('-',' ')
    text_data = text_data.replace("/",' ')
    text_data = text_data.replace(">",' ')
    text_data = text_data.replace('"',' ')
    text_data = text_data.replace('?',' ')
    return text_data

In [7]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>

False

In [19]:
from nltk.stem.snowball import SnowballStemmer

In [20]:
  
# loading stop words from nltk library

stop_words = set(stopwords.words('english'))
stemmer = SnowballStemmer('english')

#removing 'no' from the stop words list as there is an importance of 'side effects' and 'no side effects' in review
stop_words.remove('no')

In [21]:
#function for text lowering 
def text_lowering(text):
    return text.lower()

In [22]:
train_data_cleaned['lowered_review'] = train_data_cleaned['review'].apply(text_lowering)

In [23]:
train_data_cleaned.head()

,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review
0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27,"""it has no side effect, i take it in combinati..."
1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,"""my son is halfway through his fourth week of ..."
2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,"""i used to take another oral contraceptive, wh..."
3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,"""this is my first time using any form of birth..."
4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37,"""suboxone has completely turned my life around..."

In [24]:
def punct_remove(text):
    translator = str.maketrans('', '', string.punctuation)
    cleaned_text = text.translate(translator)
    return cleaned_text

In [25]:
train_data_cleaned['remove_punctuation_review']=train_data_cleaned['lowered_review'].apply(punct_remove)

In [26]:
train_data_cleaned.head()

,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review
0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27,"""it has no side effect, i take it in combinati...",it has no side effect i take it in combination...
1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,"""my son is halfway through his fourth week of ...",my son is halfway through his fourth week of i...
2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,"""i used to take another oral contraceptive, wh...",i used to take another oral contraceptive whic...
3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,"""this is my first time using any form of birth...",this is my first time using any form of birth ...
4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37,"""suboxone has completely turned my life around...",suboxone has completely turned my life around ...

In [27]:
def remove_stopwords(review):
    '''This functional block preprocess the text data by removing digits, extra spaces, stop words 
    and converting words to lower case and stemming words'''
    
    if type(review) is not int:
        string = ""
        review = preprocess_text(review)
        review = re.sub('[^a-zA-Z]', ' ', review)
        review = re.sub('\s+',' ', review)
        review = review.lower()
        for word in review.split():
            if not word in stop_words:
                word = stemmer.stem(word)
                string += word + " "
        return string

In [28]:
train_data_cleaned['stopwords_remove_review']=train_data_cleaned['remove_punctuation_review'].apply(remove_stopwords)

In [29]:
train_data_cleaned.head()

,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review,stopwords_remove_review
0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27,"""it has no side effect, i take it in combinati...",it has no side effect i take it in combination...,no side effect take combin bystol mg fish oil
1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,"""my son is halfway through his fourth week of ...",my son is halfway through his fourth week of i...,son halfway fourth week intuniv becam concern ...
2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,"""i used to take another oral contraceptive, wh...",i used to take another oral contraceptive whic...,use take anoth oral contracept pill cycl happi...
3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,"""this is my first time using any form of birth...",this is my first time using any form of birth ...,first time use form birth control glad went pa...
4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37,"""suboxone has completely turned my life around...",suboxone has completely turned my life around ...,suboxon complet turn life around feel healthie...

In [30]:
from nltk.tokenize import word_tokenize

In [31]:
def tokenize_word(text):
    return word_tokenize(text)

In [32]:
train_data_cleaned['tokenized_review']=train_data_cleaned['stopwords_remove_review'].apply(tokenize_word)

In [33]:
train_data_cleaned.head()

,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review,stopwords_remove_review,tokenized_review
0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27,"""it has no side effect, i take it in combinati...",it has no side effect i take it in combination...,no side effect take combin bystol mg fish oil,"[no, side, effect, take, combin, bystol, mg, f..."
1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192,"""my son is halfway through his fourth week of ...",my son is halfway through his fourth week of i...,son halfway fourth week intuniv becam concern ...,"[son, halfway, fourth, week, intuniv, becam, c..."
2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17,"""i used to take another oral contraceptive, wh...",i used to take another oral contraceptive whic...,use take anoth oral contracept pill cycl happi...,"[use, take, anoth, oral, contracept, pill, cyc..."
3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10,"""this is my first time using any form of birth...",this is my first time using any form of birth ...,first time use form birth control glad went pa...,"[first, time, use, form, birth, control, glad,..."
4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37,"""suboxone has completely turned my life around...",suboxone has completely turned my life around ...,suboxon complet turn life around feel healthie...,"[suboxon, complet, turn, life, around, feel, h..."

In [34]:
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [35]:
# Download NLTK resources (only needed the first time)
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
[nltk_data] Error loading wordnet: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>

False

In [36]:
# converting the date into datetime format
train_data_cleaned['date'] = pd.to_datetime(train_data_cleaned['date'], errors = 'coerce')

# extracting year from date
train_data_cleaned['Year'] = train_data_cleaned['date'].dt.year

# extracting the month from the date
train_data_cleaned['month'] = train_data_cleaned['date'].dt.month

# extracting the days from the date
train_data_cleaned['day'] = train_data_cleaned['date'].dt.day

In [37]:
train_data_cleaned.head()

,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review,stopwords_remove_review,tokenized_review,Year,month,day
0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",it has no side effect i take it in combination...,no side effect take combin bystol mg fish oil,"[no, side, effect, take, combin, bystol, mg, f...",2012,5,20
1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",my son is halfway through his fourth week of i...,son halfway fourth week intuniv becam concern ...,"[son, halfway, fourth, week, intuniv, becam, c...",2010,4,27
2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",i used to take another oral contraceptive whic...,use take anoth oral contracept pill cycl happi...,"[use, take, anoth, oral, contracept, pill, cyc...",2009,12,14
3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",this is my first time using any form of birth ...,first time use form birth control glad went pa...,"[first, time, use, form, birth, control, glad,...",2015,11,3
4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",suboxone has completely turned my life around ...,suboxon complet turn life around feel healthie...,"[suboxon, complet, turn, life, around, feel, h...",2016,11,27

In [39]:
train_data_cleaned.to_csv('data/processed_data/drugsComTrain_feature_engineering.csv')