In [1]:
import pandas as pd 
import numpy as np

In [2]:
processed_data = pd.read_csv("data/processed_data/drugsComTrain_feature_engineering.csv")

In [3]:
processed_data.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review,stopwords_remove_review,tokenized_review,Year,month,day
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",it has no side effect i take it in combination...,no side effect take combin bystol mg fish oil,"['no', 'side', 'effect', 'take', 'combin', 'by...",2012,5,20
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",my son is halfway through his fourth week of i...,son halfway fourth week intuniv becam concern ...,"['son', 'halfway', 'fourth', 'week', 'intuniv'...",2010,4,27
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",i used to take another oral contraceptive whic...,use take anoth oral contracept pill cycl happi...,"['use', 'take', 'anoth', 'oral', 'contracept',...",2009,12,14
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",this is my first time using any form of birth ...,first time use form birth control glad went pa...,"['first', 'time', 'use', 'form', 'birth', 'con...",2015,11,3
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",suboxone has completely turned my life around ...,suboxon complet turn life around feel healthie...,"['suboxon', 'complet', 'turn', 'life', 'around...",2016,11,27

In [4]:
from textblob import TextBlob, Word, Blobber
from nltk.stem import PorterStemmer
st = PorterStemmer()

In [5]:
rows_with_floats = processed_data[processed_data['stopwords_remove_review'].apply(lambda x: isinstance(x, float))]

In [6]:
rows_with_floats

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review,stopwords_remove_review,tokenized_review,Year,month,day
10542,10542,10605,158432,Methylphenidate,atigue,"""A+++""",8.0,2015-06-14,7,"""a+++""",a,NaN,[],2015,6,14
42656,42656,42909,194916,Levetiracetam,Neuralgia,"""I""",9.0,2014-02-23,2,"""i""",i,NaN,[],2014,2,23
113147,113147,113792,74792,Keppra,Neuralgia,"""I""",9.0,2014-02-23,2,"""i""",i,NaN,[],2014,2,23
122471,122471,123174,180087,Ifosfamide,Testicular Cance,"""-""",10.0,2017-01-08,0,"""-""",NaN,NaN,[],2017,1,8
127919,127919,128652,116477,Ifex,Testicular Cance,"""-""",10.0,2017-01-08,0,"""-""",NaN,NaN,[],2017,1,8
142797,142797,143619,172398,Clonazepam,Anxiety,"""I""",8.0,2016-10-19,3,"""i""",i,NaN,[],2016,10,19

In [7]:
# remove null values 
processed_data_new = processed_data[processed_data['stopwords_remove_review'].notna()]

In [8]:
processed_data_new['stemmed_review'] = processed_data_new['stopwords_remove_review'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\4099881397.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['stemmed_review'] = processed_data_new['stopwords_remove_review'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

In [9]:
processed_data_new.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review,stopwords_remove_review,tokenized_review,Year,month,day,stemmed_review
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",it has no side effect i take it in combination...,no side effect take combin bystol mg fish oil,"['no', 'side', 'effect', 'take', 'combin', 'by...",2012,5,20,no side effect take combin bystol mg fish oil
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",my son is halfway through his fourth week of i...,son halfway fourth week intuniv becam concern ...,"['son', 'halfway', 'fourth', 'week', 'intuniv'...",2010,4,27,son halfway fourth week intuniv becam concern ...
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",i used to take another oral contraceptive whic...,use take anoth oral contracept pill cycl happi...,"['use', 'take', 'anoth', 'oral', 'contracept',...",2009,12,14,use take anoth oral contracept pill cycl happi...
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",this is my first time using any form of birth ...,first time use form birth control glad went pa...,"['first', 'time', 'use', 'form', 'birth', 'con...",2015,11,3,first time use form birth control glad went pa...
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",suboxone has completely turned my life around ...,suboxon complet turn life around feel healthie...,"['suboxon', 'complet', 'turn', 'life', 'around...",2016,11,27,suboxon complet turn life around feel healthie...

In [10]:
processed_data_new['lemmatized_review'] = processed_data_new['stopwords_remove_review'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))

C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\3454577232.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['lemmatized_review'] = processed_data_new['stopwords_remove_review'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))

In [11]:
processed_data_new.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review,stopwords_remove_review,tokenized_review,Year,month,day,stemmed_review,lemmatized_review
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",it has no side effect i take it in combination...,no side effect take combin bystol mg fish oil,"['no', 'side', 'effect', 'take', 'combin', 'by...",2012,5,20,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",my son is halfway through his fourth week of i...,son halfway fourth week intuniv becam concern ...,"['son', 'halfway', 'fourth', 'week', 'intuniv'...",2010,4,27,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",i used to take another oral contraceptive whic...,use take anoth oral contracept pill cycl happi...,"['use', 'take', 'anoth', 'oral', 'contracept',...",2009,12,14,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",this is my first time using any form of birth ...,first time use form birth control glad went pa...,"['first', 'time', 'use', 'form', 'birth', 'con...",2015,11,3,first time use form birth control glad went pa...,first time use form birth control glad went pa...
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",suboxone has completely turned my life around ...,suboxon complet turn life around feel healthie...,"['suboxon', 'complet', 'turn', 'life', 'around...",2016,11,27,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...

In [12]:
processed_data_new['review_len'] = processed_data_new['stopwords_remove_review'].astype(str).apply(len)
processed_data_new['stemmed_review_len'] = processed_data_new['stemmed_review'].astype(str).apply(len)
processed_data_new['lem_review_len'] = processed_data_new['lemmatized_review'].astype(str).apply(len)

C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\1947839832.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['review_len'] = processed_data_new['stopwords_remove_review'].astype(str).apply(len)
C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\1947839832.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['stemmed_review_len'] = processed_data_new['stemmed_review'].astype(str).apply(len)
C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\1947839832.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['lem_review_len'] = processed_data_new['lemmatized_review'].astype(str).apply(len)

In [13]:
processed_data_new.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,...,stopwords_remove_review,tokenized_review,Year,month,day,stemmed_review,lemmatized_review,review_len,stemmed_review_len,lem_review_len
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",...,no side effect take combin bystol mg fish oil,"['no', 'side', 'effect', 'take', 'combin', 'by...",2012,5,20,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil,46,45,45
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",...,son halfway fourth week intuniv becam concern ...,"['son', 'halfway', 'fourth', 'week', 'intuniv'...",2010,4,27,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...,372,369,367
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",...,use take anoth oral contracept pill cycl happi...,"['use', 'take', 'anoth', 'oral', 'contracept',...",2009,12,14,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...,403,401,401
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",...,first time use form birth control glad went pa...,"['first', 'time', 'use', 'form', 'birth', 'con...",2015,11,3,first time use form birth control glad went pa...,first time use form birth control glad went pa...,226,223,225
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",...,suboxon complet turn life around feel healthie...,"['suboxon', 'complet', 'turn', 'life', 'around...",2016,11,27,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...,380,378,379

In [14]:
processed_data_new['word_count'] =processed_data_new['stopwords_remove_review'].apply(lambda x: len(str(x).split()))

C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\4257297749.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['word_count'] =processed_data_new['stopwords_remove_review'].apply(lambda x: len(str(x).split()))

In [15]:
processed_data_new.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,...,tokenized_review,Year,month,day,stemmed_review,lemmatized_review,review_len,stemmed_review_len,lem_review_len,word_count
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",...,"['no', 'side', 'effect', 'take', 'combin', 'by...",2012,5,20,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil,46,45,45,9
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",...,"['son', 'halfway', 'fourth', 'week', 'intuniv'...",2010,4,27,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...,372,369,367,65
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",...,"['use', 'take', 'anoth', 'oral', 'contracept',...",2009,12,14,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...,403,401,401,70
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",...,"['first', 'time', 'use', 'form', 'birth', 'con...",2015,11,3,first time use form birth control glad went pa...,first time use form birth control glad went pa...,226,223,225,39
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",...,"['suboxon', 'complet', 'turn', 'life', 'around...",2016,11,27,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...,380,378,379,58

TO IDENTIFY SENTIMENT POLARITY

VADER:

In [16]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Error loading vader_lexicon: <urlopen error [WinError
[nltk_data]     10060] A connection attempt failed because the
[nltk_data]     connected party did not properly respond after a
[nltk_data]     period of time, or established connection failed
[nltk_data]     because connected host has failed to respond>

False

In [17]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [18]:
sid = SentimentIntensityAnalyzer()

In [19]:
def vader_sentiment(text):
    return sid.polarity_scores(text).get('compound')

In [20]:
processed_data_new['sentiment_vader'] = processed_data_new['stopwords_remove_review'].apply(vader_sentiment)

C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\913085462.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['sentiment_vader'] = processed_data_new['stopwords_remove_review'].apply(vader_sentiment)

In [21]:
processed_data_new.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,...,Year,month,day,stemmed_review,lemmatized_review,review_len,stemmed_review_len,lem_review_len,word_count,sentiment_vader
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",...,2012,5,20,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil,46,45,45,9,-0.2960
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",...,2010,4,27,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...,372,369,367,65,0.6929
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",...,2009,12,14,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...,403,401,401,70,0.2732
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",...,2015,11,3,first time use form birth control glad went pa...,first time use form birth control glad went pa...,226,223,225,39,0.1027
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",...,2016,11,27,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...,380,378,379,58,0.8934

In [22]:
def vader_classify(compound_score):
    if compound_score >= 0.05:
        sentiment= 'Positive'
    elif compound_score <= -0.05:
        sentiment= 'Negative'
    else:
        sentiment='Neutral'
    return sentiment

In [23]:
processed_data_new['sentiment_vader_label'] = processed_data_new['sentiment_vader'].apply(vader_classify)

C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\2634933971.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['sentiment_vader_label'] = processed_data_new['sentiment_vader'].apply(vader_classify)

In [24]:
processed_data_new.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,...,month,day,stemmed_review,lemmatized_review,review_len,stemmed_review_len,lem_review_len,word_count,sentiment_vader,sentiment_vader_label
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",...,5,20,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil,46,45,45,9,-0.2960,Negative
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",...,4,27,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...,372,369,367,65,0.6929,Positive
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",...,12,14,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...,403,401,401,70,0.2732,Positive
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",...,11,3,first time use form birth control glad went pa...,first time use form birth control glad went pa...,226,223,225,39,0.1027,Positive
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",...,11,27,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...,380,378,379,58,0.8934,Positive

In [25]:
from textblob import TextBlob

In [26]:

def Textblob_sentiment(text):
    return TextBlob(text).sentiment.polarity

In [27]:
processed_data_new['sentiment_textblob'] = processed_data_new['stopwords_remove_review'].apply(Textblob_sentiment)

C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\3166297703.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['sentiment_textblob'] = processed_data_new['stopwords_remove_review'].apply(Textblob_sentiment)

In [28]:
processed_data_new.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,...,day,stemmed_review,lemmatized_review,review_len,stemmed_review_len,lem_review_len,word_count,sentiment_vader,sentiment_vader_label,sentiment_textblob
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",...,20,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil,46,45,45,9,-0.2960,Negative,0.000000
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",...,27,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...,372,369,367,65,0.6929,Positive,0.114583
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",...,14,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...,403,401,401,70,0.2732,Positive,0.105000
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",...,3,first time use form birth control glad went pa...,first time use form birth control glad went pa...,226,223,225,39,0.1027,Positive,0.300000
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",...,27,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...,380,378,379,58,0.8934,Positive,0.147037

In [29]:
def textblob_classify(polarity):
    if polarity > 0:
        sentiment = 'positive'
    elif polarity == 0:
        sentiment = 'neutral'
    else:
        sentiment = 'negative'
    return sentiment

In [30]:
processed_data_new['sentiment_textblob_label'] = processed_data_new['sentiment_textblob'].apply(textblob_classify)

C:\Users\Ramya\AppData\Local\Temp\ipykernel_12444\3907915554.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  processed_data_new['sentiment_textblob_label'] = processed_data_new['sentiment_textblob'].apply(textblob_classify)

In [31]:
processed_data_new.head()

,Unnamed: 0.1,Unnamed: 0,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,...,stemmed_review,lemmatized_review,review_len,stemmed_review_len,lem_review_len,word_count,sentiment_vader,sentiment_vader_label,sentiment_textblob,sentiment_textblob_label
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",...,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil,46,45,45,9,-0.2960,Negative,0.000000,neutral
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",...,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...,372,369,367,65,0.6929,Positive,0.114583,positive
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",...,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...,403,401,401,70,0.2732,Positive,0.105000,positive
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",...,first time use form birth control glad went pa...,first time use form birth control glad went pa...,226,223,225,39,0.1027,Positive,0.300000,positive
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",...,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...,380,378,379,58,0.8934,Positive,0.147037,positive

In [32]:
processed_data_new = processed_data_new.drop(['Unnamed: 0'],axis=1)

In [33]:
processed_data_new.head()

,Unnamed: 0.1,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,remove_punctuation_review,...,stemmed_review,lemmatized_review,review_len,stemmed_review_len,lem_review_len,word_count,sentiment_vader,sentiment_vader_label,sentiment_textblob,sentiment_textblob_label
0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",it has no side effect i take it in combination...,...,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil,46,45,45,9,-0.2960,Negative,0.000000,neutral
1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",my son is halfway through his fourth week of i...,...,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...,372,369,367,65,0.6929,Positive,0.114583,positive
2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",i used to take another oral contraceptive whic...,...,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...,403,401,401,70,0.2732,Positive,0.105000,positive
3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",this is my first time using any form of birth ...,...,first time use form birth control glad went pa...,first time use form birth control glad went pa...,226,223,225,39,0.1027,Positive,0.300000,positive
4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",suboxone has completely turned my life around ...,...,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...,380,378,379,58,0.8934,Positive,0.147037,positive

In [34]:
processed_data_new['sentiment_vader_label'].value_counts()

sentiment_vader_label
Positive    77081
Negative    73372
Neutral      9939
Name: count, dtype: int64

In [35]:
processed_data_new['sentiment_textblob_label'].value_counts()

sentiment_textblob_label
positive    101064
negative     42899
neutral      16429
Name: count, dtype: int64

In [37]:
processed_data_new.to_csv('data/processed_data/drugsComTrain_text_preprocessing.csv')